baseURL = 'https://migus.org/'
enableEmoji = true
enableRobotsTXT = true
languageCode = 'en-us'
title = 'migus.org'
author = 'Adam Migus'
copyright = 'Â©2024, 2025 Adam Migus'
[markup]
  [markup.goldmark]
    [markup.goldmark.parser]
      [markup.goldmark.parser.attribute]
        block = true
  [markup.highlight]
    style = 'rrt'
[params]
  [params.fonts]
    [params.fonts.google]
      sans = 'Fira Sans'
      mono = 'Fira Mono'
      extras = []

[services]
  [services.googleAnalytics]
    id = 'G-0H4BE185DF'
